config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/welcome"
  resources :abstracts, only: [:index] #admin only
  resources :users do
      resources :abstracts, only: [:new, :create, :edit, :update]
      resources :participations do
        get 'profile'
        resources :abstracts, only: [:show]
      end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  #belongs_to :conference
  belongs_to :user
  belongs_to :abstract


  KINDS = { regular_local_new_member: "Regular Local New Member",
            regular_local: "Regular Local",
            student_local: "Student Local",
            regular_foreign: "Regular Foreign",
            student_foreign: "Student Foreign",
            invited_speaker: "Invited Speaker",
            plenary_speaker: "Plenary Speaker",
            exhibitor: "Exhibitor",
            other: "Other"
  }

  enum kind: KINDS
  #validates_inclusion_of :kind, in: HashWithIndifferentAccess.new(KINDS).keys
  #validates :kind, :fee, presence: true, on: :create

  before_update :set_fee
  def set_fee
    kind = self.kind
    case kind
    when "regular_local_new_member" || "student_local"
      self.fee = "Php 500"
    when "regular_local"
      self.fee = "Php 1000"
    when "student_foreign"
      self.fee = "USD 50"
    when "regular_foreign"
      self.fee = "USD 100"
    when "invited_speaker" || "plenary_speaker" || "exhibitor"
      self.fee = "Your participation is not subject to conference fee."
    when "other"
      self.fee = "Please contact us for details."
    end
  end

  #if user has no existing abstracts, set participation kind to default
  before_create :set_default_kind
  def set_default_kind
    self.kind = "other"
    set_fee
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :authenticate_user!


  def show
    @user =  User.find(params[:user_id])
    @abstracts = @user.abstracts.all
    @participation = @user.participations.find(params[:id])
  end

  def profile
    @user =  User.find(params[:user_id])
    @abstracts = @user.abstracts.all
    @participation = @user.participations.find(params[:participation_id])
  end

  def edit
    @user =  User.find(params[:user_id])
    @participation = @user.participations.find(params[:id])
  end

  def update
    @user =  User.find(params[:user_id])
    @participation = @user.participations.find(params[:id])
    @participations = @user.participations.all

    #for multiple abstracts hence multiple participations, the changes in
    #one participation is cascaded to all participations
    #@participation.set_kind(params[:user_id], params[:participation][:kind], params[:id])
    @participations.each do |participation|
      participation.update!(kind: params[:participation][:kind])
      @participation.set_fee
    end

    #update user details without going to another link
    prefix = params[:participation][:prefix]
    first_name = params[:participation][:first_name]
    last_name = params[:participation][:last_name]
    suffix = params[:participation][:suffix]
    email = params[:participation][:email]
    position = params[:participation][:position]
    university_institute_company = params[:participation][:university_institute_company]
    department = params[:participation][:department]
    contact_number = params[:participation][:contact_number]
    city = params[:participation][:city]
    country = params[:participation][:country]
    @user.update!(prefix: prefix, first_name: first_name, last_name: last_name,
      suffix: suffix, email: email, position: position,
      university_institute_company: university_institute_company,
      department: department, contact_number: contact_number, city: city,
      country: country)

    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to user_participation_profile_path(@user, @participation),
          notice: "Your participation details successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
      end
      # rescue ActiveRecord::RecordInvalid => e
      #   return e.record
    end
  end

  private
  def participation_params
    params.require(:participation).permit(:kind)
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="card flex-column shadow p-3 mb-5 bg-body rounded" style="width: 40rem;">
    <h2 class="text-center">Register as ISVSP 2022 participant</h2>
    <p class="text-center italic"> Fill in all details unless tagged as optional and follow instructions to ensure correct format to be printed in Book of Abstracts.</p>
    <div class="form-container">
      <%= form_with model: [ @user, @participation ], local: true do |f| %>
        <% if @participation.errors.any? %>
          <div id="error_explanation">
            <h5>The form contains <%= pluralize(@participation.errors.count, "error") %></h5>
            <ul>
              <% @participation.errors.full_messages.each do |m| %>
                <li><%= m %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-group mb-6">
          <%= f.label :prefix %><br />
          <%= f.select :prefix, options_for_select(User::TYPES, :selected => @user.prefix), { }, { class: "form-select form-select-md mb-6" } %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name",
              value: @user.first_name, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name",
              value: @user.last_name, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :suffix %> (Optional)<br />
          <%= f.text_field :suffix, autofocus: true, autocomplete: "suffix",
              placeholder: "Jr., I, CBE etc", value: @user.suffix, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email",
              value: @user.email, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :position %><br />
          <%= f.select :position, options_for_select(User.positions.map { |p| [p.last, p.last]},
              :selected => @user.position.humanize), {},
              { class: "form-select form-select-md mb-6" } %>
        </div>

        <div class="field form-group mb-6">
          University, Institute or Company Name
          <%= f.text_field :university_institute_company, autofocus: true,
            autocomplete: "university_institute_company",
            value: @user.university_institute_company, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :department %><br />
          <%= f.text_field :department, autofocus: true, autocomplete: "department",
            value: @user.department, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :city %><br />
          <%= f.text_field :city, autofocus: true,
              autocomplete: "contact_number", value: @user.city,
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :country %><br />
          <%= f.text_field :country, autofocus: true,
              autocomplete: "contact_number", value: @user.country,
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          Contact Number
          <%= f.telephone_field :contact_number, autofocus: true,
              autocomplete: "contact_number", value: @user.contact_number,
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          Register as <br />
          <%= f.select :kind, options_for_select(Participation.kinds.map { |k| [k.last, k.last]},
          :selected => @participation.kind ), {}, { class: "form-select form-select-md mb-6" } %>
        </div>

        <div class="actions d-flex justify-content-center pt-1">
          <%= f.submit "Submit", class: "btn btn-gray btn-margin btn-wide" %>
        </div>
        <div class="actions d-flex justify-content-center pt-1">
          <%= link_to 'My Conference Profile', user_participation_profile_path(@user, @participation),
          class: "btn btn-gray btn-margin btn-wide" %>
        </div>
      <% end %>
    </div>
  </div>
</div>


app/views/participations/profile.html.erb
<div class="home-container p-4 bg-white">
  <!-- <h1 class="card-title task-title text-center">Welcome <%= current_user.prefix %> <%= current_user.last_name %>!</h1> -->
  <% if user_signed_in? %>
  <div class="justify-content-center">
    <h1 class="card-title text-center">My Conference Profile</h1>
    <p class="card-text text-center italic small-text"> Kindly review your profile for completeness and accuracy. This will be used for Book of Abstracts and Program Details. You may edit by clicking the button below.</p>
    <p class="card-text">Prefix: <%= current_user.prefix %></p>
    <p class="card-text">First Name: <%= current_user.first_name  %></p>
    <p class="card-text">Last Name: <%= current_user.last_name %></p>
    <p class="card-text">Suffix: <%= current_user.suffix %></p>
    <p class="card-text">Position: <%= current_user.position.humanize %></p>
    <p class="card-text">University, Institute or Company: <%= current_user.university_institute_company %></p>
    <p class="card-text">Department: <%= current_user.department %></p>
    <p class="card-text">City: <%= current_user.city %></p>
    <p class="card-text">Country: <%= current_user.country %></p>
    <p class="card-text">Contact Number: <%= current_user.contact_number %></p>

    <h3 class="card-title text-center">My ISVSP 2022 Participation</h3>
    <p class="card-text text-center italic small-text"> Conference fee depends on registration type, please edit accordingly or contact us for more details.</p>
    <p class="card-text">Registered as: <%= @participation.kind.humanize%></p>
    <p class="card-text">Fee: <%= @participation.fee %></p>
  </div>

  <div class="actions d-flex justify-content-center py-4">
    <%= link_to "Edit my conference profile details", edit_user_participation_path(@user, @participation.id), class: "btn btn-gray text-center" %>
  </div>
    <div class="table-container bg-white">
      <h3 class="text-center">My Abstracts: <%=@abstracts.count %></h3>
      <p class="card-text text-center italic small-text"> You may review each of your submitted abstracts by clicking on the title.</p>
      <table class="table table-hover table-responsive-md text">
        <thead class="text-gray text-center">
        <tr>
          <th scope="col">Title</th>
        </tr>
        </thead>
        <tbody>
          <% @abstracts.each do |abstract| %>
            <tr>
              <td class="text">
                <%= link_to abstract.title, user_participation_abstract_path(@user, @participation.id, abstract.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>


app/views/participations/show.html.erb
<div class="table-container p-4 bg-white">
  <h1>Welcome <%= current_user.prefix %> <%= current_user.last_name %>!</h1>
  <% if user_signed_in? %>
    <h3 class="card-title task-title">My ISVSP 2022 Participation</h3>
    <p class="card-text">Registered as: <%= @participation.kind.humanize%></p>
    <p class="card-text">Fee: <%= @participation.fee %></p>

    <%= link_to "Edit my conference participation type", edit_user_participation_path(@user, @participation.id), class: "btn btn-gray" %>
  <% end %>
</div>