config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/welcome"
  resources :abstracts, only: [:index] #admin only
  resources :users do
      resources :abstracts, only: [:new, :create, :edit, :update]
      resources :participations do
        get 'profile'
        resources :abstracts, only: [:show]
      end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def welcome
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="home-container">
    <h1 class="title">The International Symposium of the Vacuum Society of the Philippines (ISVSP 2022)</h1>
    <h4 class="description">3-5 February 2022</h4>
    <h4 class="description italic">Refocusing vacuum and plasma technology to the current needs of the society.</h4>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-gray btn-home" %>
</div>

app/views/static_pages/welcome.html.erb
<div class="table-container p-4 bg-white">
  <% if user_signed_in?  %>
    <h2 class="text-center">Welcome <%= current_user.prefix %> <%= current_user.last_name %></h2>
    <%# link_to 'Register as Conference Participant Now', user_participation_path(current_user.id), class: "btn btn-gray" %>
    <% if current_user.admin? %>
      <%= link_to "Users List", users_path, class: "btn btn-gray btn-navs" %>
      <%= link_to "Abstracts List", abstracts_path, class: "btn btn-gray btn-navs" %>
    <% end %>
  <% else %>
      <%= link_to "Sign Up or Login ", root_path, class: "btn btn-gray btn-navs" %>
  <% end %>

  <%= link_to "Submit an Abstract", new_user_abstract_path(current_user), class: "btn btn-gray btn-navs" %>
</div>