config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/welcome"
  resources :abstracts, only: [:index] #admin only
  resources :users do
      resources :abstracts, only: [:new, :create, :edit, :update]
      resources :participations do
        get 'profile'
        resources :abstracts, only: [:show]
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable


  TYPES = %w(Dr. Ms. Mr. Mrs. Prof. Sir Dame).freeze
  validates :prefix, :inclusion => {:in => TYPES}
  validates :prefix,:first_name,:last_name, :email, :password, :password_confirmation,
            presence: true, on: :create

  PASSWORD_FORMAT = /\A #Start of string
    (?=.{6,}) # at least 6 characters
    (?=.*\d)  # at least one number
    (?=.*[a-z]) # at least one lowercase letter
    (?=.*[A-Z]) # at least one uppercase letter
    (?=.*[[:^alnum:]]) # have at least one symbol
  /x #End of string

  #check the password complexity on create
  validates :password, length: { in: Devise.password_length }, format: PASSWORD_FORMAT,
            confirmation: true, on: :create

  validates :password_confirmation, format: PASSWORD_FORMAT, on: :create

  #callback for sending email notification
  after_create :send_email

  def send_email
    UserMailer.welcome_email(self).deliver_later
  end

  has_many :participations, dependent: :destroy
  #has_many :conferences, through: :participations, dependent: :destroy
  has_many :abstracts, through: :participations, dependent: :destroy

  #format for the select option in form
  def get_fullname
    "#{prefix} #{first_name} #{last_name} #{suffix}"
  end

  POSITIONS = { research_scientist: "Research Scientist",
                professor: "Professor",
                phd: "PhD",
                faculty: "Faculty",
                doctoral_student: "Doctoral Student",
                masteral_student: "Masteral Student",
                college_student: "College Student",
                highschool_student: "High School Student",
                other: "Other"
  }.freeze
  #this saves as nil in db :((
  # POSITIONS = { reseach_scientist: 0,
  #               professor: 1,
  #                  phd: 2,
  #                  faculty: 3,
  #                  doctoral_student: 4,
  #                  masteral_student: 5,
  #                  college_student: 6,
  #                  highschool_student: 7,
  #                  other: 8
  #                   }
  enum position: POSITIONS
  #source for below: https://stackoverflow.com/questions/43840080/rails-enum-validation-failing
  validates_inclusion_of :position, in: HashWithIndifferentAccess.new(POSITIONS).keys
  validates :prefix,:first_name,:last_name, :email, :position,:university_institute_company, :department,
    :contact_number, :city, :country,  presence: true, on: :update
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin, only: %i[index]
  before_action :set_user, only: %i[show edit update]

  def index
    @users = User.all
    respond_to do |format|
      format.xlsx {
        render :xlsx => "index", :filename => "all_users.xlsx"
      }
      format.html { render :index }
    end
  end

  def show
    #@participations = @user.participations.all
  end

  def edit
    @participation = @user.abstracts.first
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "#{@user.prefix} #{@user.last_name}'s' details successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def is_admin
    unless current_user.admin?
      redirect_to static_pages_welcome_path,
      notice: "Unauthorized access."
    end
  end

  def set_user
      @user = User.find(params[:id])
      @abstracts = @user.abstracts.all
  end

  def user_params
    params.require(:user).permit(:prefix, :prefix,:first_name,:last_name,
          :email, :position, :university_institute_company, :department,
          :contact_number)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="title">
  <h2>ISVSP 2022 Participation</h2>
</div>
<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h5>The form contains <%= pluralize(@user.errors.count, "error") %></h5>
      <ul>
        <% @user.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-6">
    <%= f.label :prefix %><br />
    <%= f.select :prefix, User::TYPES, { }, { class: "form-select form-select-md mb-6" } %>
  </div>

  <div class="field form-group mb-6">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name",
        class: "form-control" %>
  </div>

  <div class="field form-group mb-6">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name",
        class: "form-control" %>
  </div>

  <div class="field form-group mb-6">
    <%= f.label :suffix %><br />
    <%= f.text_field :suffix, autofocus: true, autocomplete: "suffix",
        placeholder: "Jr., I, CBE etc", class: "form-control" %>
  </div>

  <div class="field form-group mb-6">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email",
        class: "form-control" %>
  </div>

  <div class="field form-group mb-6">
    <%= f.label :position %><br />
    <%# f.text_field :position, autofocus: true, autocomplete: "position",
        class: "form-control" %>
    <%= f.select :position, User.positions.map { |p| [p.last, p.last]}, {}, { class: "form-select form-select-md mb-6" } %>
  </div>

  <div class="field form-group mb-6">
    University, Institute or Company Name
    <%= f.text_field :university_institute_company, autofocus: true, autocomplete: "university_institute_company", class: "form-control" %>
  </div>

  <div class="field form-group mb-6">
    <%= f.label :department %><br />
    <%= f.text_field :department, autofocus: true, autocomplete: "department", class: "form-control" %>
  </div>

  <div class="field form-group mb-6">
    Contact Number
    <%= f.telephone_field :contact_number, autofocus: true, autocomplete: "contact_number", class: "form-control" %>
  </div>

   <h2>Register to ISVSP 2022</h2>
  <div class="field form-group mb-6">
    <%= f.fields_for :participations, @user.participations.build do |participation_subform_fields| %>
      <div class="field form-group mb-6">
        <%# participation_subform_fields.label :kind %><br />
        <%= participation_subform_fields.number_field :abstract_id, step: 1, value:@user.abstracts.first.id,  type: "hidden", class: "form-control" %>
        <%# binding.pry %>
      </div>

      <div class="field form-group mb-6">
        Register as <%# participation_subform_fields.label :kind %><br />
        <%= participation_subform_fields.select :kind, Participation.kinds.map { |k| [k.last, k.last]}, {}, { class: "form-select form-select-md mb-6" } %>
      </div>
    <% end %>
  </div>

  <!-- <div>
    <h2>Abstract Submission</h2>
    <div class="field form-group mb-6">
      <%= f.fields_for :abstracts, @user.abstracts.build do |abstract_subform_fields| %>

        <div class="field form-group mb-6">
          <%= abstract_subform_fields.label :title %><br />
          <%= abstract_subform_fields.text_field :title, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= abstract_subform_fields.label :main_author %><br />
          <%= abstract_subform_fields.text_field :main_author, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= abstract_subform_fields.label :co_authors %><br />
          <%= abstract_subform_fields.text_field :co_authors, class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= abstract_subform_fields.label :co_authors1 %><br />
          <%= abstract_subform_fields.select( :co_authors1, User.all.collect {|user| [user.co_author_properties, user.co_author_properties ]}, {}, { :multiple=> true, class: "form-select form-select-md mb-6" } )%>
        </div>

        <div class="field form-group mb-6">
          <%= abstract_subform_fields.label :body %><br />
          <%= abstract_subform_fields.text_area :body, size: "25x10", class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div> -->

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-gray" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="table-container p-4 bg-white">
  <h3 class="text-center">All users: <%= @users.count %></h3>
  <p class="text-center">
    <%= link_to 'Download as Excel', users_path(format: :xlsx)%>
  </p>
  <table class="table table-hover table-responsive-md text">
    <thead>
    <tr>
      <th scope="col">Prefix</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="text"><%= user.prefix %></td>
          <td class="text"><%= user.first_name %></td>
          <td class="text"><%= user.last_name %></td>
          <td class="text"><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="table-container p-4 bg-white">
  <h1>Welcome <%= current_user.prefix %> <%= current_user.last_name %>!</h1>
  <% if user_signed_in? %>
    <h5 class="card-title task-title"></h5>
    <p class="card-text">Prefix: <%= current_user.prefix %></p>
    <p class="card-text">First Name: <%= current_user.first_name  %></p>
    <p class="card-text">Last Name: <%= current_user.last_name %></p>
    <p class="card-text">Suffix: <%= current_user.suffix %></p>
    <p class="card-text">Position: <%= current_user.position.humanize %></p>
    <p class="card-text">University, Institute or Company: <%= current_user.university_institute_company %></p>
    <p class="card-text">Department: <%= current_user.department %></p>

    <!-- <h3 class="text-center">My Abtracts: <%= @abstracts.count %></h3>
    <table class="table table-hover table-responsive-md text">
      <thead>
      <tr>
        <th scope="col">Title</th>
      </tr>
      </thead>
      <tbody>
        <%# @abstracts.each do |abstract| %>
          <tr>
            <td class="text"><%# link_to abstract.title, user_participation_abstract_path(@user, @participation.id,abstract.id) %></td>
          </tr>
        <%# end %>
      </tbody>
    </table>-->
    <p><%# link_to 'Edit My Details', edit_user_path(@user.id), class: "btn btn-gray" %></p>
  <% end %>
</div>