config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/welcome"
  resources :abstracts, only: [:index] #admin only
  resources :users do
      resources :abstracts, only: [:new, :create, :edit, :update]
      resources :participations do
        get 'profile'
        resources :abstracts, only: [:show]
      end
  end
end

app/models/abstract.rb
class Abstract < ApplicationRecord
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations, dependent: :destroy

  #transform the input to desired format before save to db
  def format_params_field(name, params_fields, abstract)
    data =[]
    case name
    when :co_authors
      params_fields.reject(&:empty?).each do |params_field|
        data << params_field
      end
      abstract.update!(co_authors: data)
    when :references
      params_fields.split("\r\n").each do |params_field|
        data << params_field
      end
      abstract.update!(references: data)
      #binding.pry
    when :keywords
      params_fields.split(",").reject(&:empty?).each do |params_field|
        data << params_field
        #binding.pry
      end
      abstract.update!(keywords: data)
    else
      puts "Please edit abstract according to instructions."
    end
  end

  #get the co_authors without formatting
  def retrieve_co_authors(user_ids)
    @co_authors = []
    user_ids.each do |user_id|
      @co_authors << User.find(user_id)
    end
    #binding.pry
    return @co_authors  #array of user hashes
  end

  #format the co_authors name for view template
  def format_fullname(co_authors)
    data = co_authors.pluck(:first_name,:last_name)
    fullname_items = []
    fullname = ""
    first_name = ""
    last_name = ""
    data.each do |sub_array|
      first_name = sub_array[0]
      last_name  = sub_array[1].upcase
      fullname = first_name.concat(" #{last_name}")
      fullname_items << fullname
    end
    #binding.pry
    return fullname_items
  end

  def format_affiliation(co_authors)
    data = co_authors.pluck(:department, :university_institute_company, :city, :country)
    affiliation_items = []
    department = ""
    university_institute_company = ""
    city = ""
    country = ""
    affiliation = ""
    data.each do |sub_array|
      department = sub_array[0]
      university_institute_company = sub_array[1]
      city = sub_array[2]
      country = sub_array[3]
      affiliation = "#{department}, #{university_institute_company}, #{city}, #{country}"
      affiliation_items << affiliation
    end
    #binding.pry
    return affiliation_items
  end

  validates :title, :main_author, :co_authors, :corresponding_author_email,
    :keywords, :body, :references, presence: true

  #validate :check_keyword_delimiter
  def check_keyword_delimiter(keywords)
    if !keywords.include?(", ") #|| !self.keywords.include?(", ")
      #binding.pry
      errors.add(:keywords, "format is invalid.")
    end
  end
end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin, only: %i[index destroy]

  def index
    @abstracts = Abstract.all
    respond_to do |format|
      format.xlsx {
        render :xlsx => "index", :filename => "all_abstracts.xlsx"
      }
      format.html { render :index }
    end
  end

  def new
    @user = User.find(params[:user_id])
    #@user = current_user
    @abstract = @user.abstracts.build
  end

  def create
    @user = User.find(params[:user_id])
    #@user = current_user
    @abstract = @user.abstracts.create(abstract_params)

    #check delimiters are valid
    @abstract.check_keyword_delimiter(params[:abstract][:keywords])

    #clean up and do correct format for these fields
    @abstract.format_params_field(:co_authors, params[:abstract][:co_authors], @abstract)
    @abstract.format_params_field(:keywords, params[:abstract][:keywords], @abstract)
    @abstract.format_params_field(:references, params[:abstract][:references], @abstract)

    respond_to do |format|
      if @abstract.save
        AbstractMailer.abstract_submission(@user.id, @abstract).deliver_later
        format.html { redirect_to user_participation_abstract_path(@user, @user.participations.find_by(abstract_id: @abstract.id), @abstract),
          notice: "Abstract submission completed." }
        format.json { render :show, status: :created, location: @abstract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @abstract.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:user_id])
    #@user = current_user
    @abstract = @user.abstracts.find(params[:id])
    @participation = @user.participations.find_by(abstract_id: @abstract.id)
    #get the latest info about the co_authors from Users table
    @co_authors = @abstract.retrieve_co_authors(@abstract.co_authors)
    @co_authors_fullname = @abstract.format_fullname(@co_authors)
    @co_authors_affiliation = @abstract.format_affiliation(@co_authors)
  end

  def edit
    @user = User.find(params[:user_id])
    #@user = current_user
    @abstract = @user.abstracts.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @abstract = @user.abstracts.find(params[:id])

    respond_to do |format|
      if @abstract.update(abstract_params)
        format.html { redirect_to user_participation_abstract_path(@user, @user.participations.find_by(abstract_id: @abstract.id), @abstract),
          notice: "Your abstract details successfully updated." }
        format.json { render :show, status: :ok, location: @abstract }
      else
          format.html { render :edit, status: :unprocessable_entity  }
          format.json { render json: @abstract.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def is_admin
    unless current_user.admin?
      redirect_to static_pages_welcome_path,
      notice: "Unauthorized access."
    end
  end

  def abstract_params
    params.require(:abstract).permit(:title, :main_author, :co_authors, :corresponding_author_email, :body, :references, :keywords) #:references, :keywords,
  end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/views/abstracts/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="card flex-column shadow p-3 mb-5 bg-body rounded" style="width: 40rem;">
    <h2 class="text-center">Edit Abstract</h2>
    <p class="text-center italic"> Fill in all details unless tagged as optional and follow instructions to ensure correct format to be printed in Book of Abstracts.</p>
    <div class="form-container">
      <%= form_with model: [ @user, @abstract ], local: true do |f| %>
        <% if @abstract.errors.any? %>
          <div id="error_explanation">
            <h5>The form contains <%= pluralize(@abstract.errors.count, "error") %></h5>
            <ul>
              <% @abstract.errors.full_messages.each do |m| %>
                <li><%= m %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-group mb-6">
          <%= f.label :title, class:"bold" %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "title",
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :main_author, class:"bold" %><br />
          <%= f.select( :main_author,  options_for_select(User.all.collect {|user| [user.get_fullname, user.id ]}, :selected => params[:user_id]), {},
            { class: "form-select form-select-md mb-6" } ) %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :co_authors, class:"bold" %><br />
            <span class="italic small">
              Ensure that all your co-authors are signed up to this web page, otherwise their names will not be among the options below.
              <ul>
                <li class="italic">For one co-author: Single left click one name from options.</li>
                <li class="italic">For multiple co-authors:<br />
                  1. Single left click one name from options. <br />
                  2. Press CTRL , scroll to look for next name and left click when found. <br />
                  3. Repeat step 2 for all co-authors. Chosen names should be blue-colored. </li>
              </ul>
            </span>
          <%= f.select( :co_authors, User.all.collect {|user| [user.get_fullname, user.id ]}, {}, { :multiple=> true, class: "form-select form-select-md mb-6" } ) %>
        </div>

        <div class="field form-group mb-6">
          <span class="bold">Email:</span>
          <%= f.email_field :corresponding_author_email, autofocus: true,
              autocomplete: "email", placeholder: "example@example.com",
              class: "form-control"  %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :keywords, class:"bold" %><br />
            <span class="italic small">
                Must have maximum of five and separated by comma. Edit so that it looks exactly as below:<br />
                "vacuum, plasma, nanomaterial"
            </span>
          <%= f.text_field :keywords, autofocus: true, autocomplete: "keywords",
              placeholder: "vacuum, plasma, nanomaterial",
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :body, class:"bold" %><br />
          <%= f.text_area :body, size: "25x10", class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :references, class:"bold" %><br />
            <span class="italic small">
              Please edit and follow specific format before submit:
              <ul>
                <li class="italic ">For one reference type: <br />
                  [1] S. Trolier-McKinstry, Springer, 2008, 39-56.</li>
                <li class="italic ">For multiple references: <br />
                  [1] S. Trolier-McKinstry, Springer, 2008, 39-56.<br />
                  [2] K. Taaca and M. Vasquez Jr. Micropor. Mesopor. Mat. 2017, 241, 383-391.<br />
                  1. Type the first reference. <br />
                  2. Press ENTER and type the next reference. <br />
                  3. Repeat step 2 for all references. <br /></li>
              </ul>
            </span>
          <%= f.text_area :references, size: "25x3", placeholder: "[1] K. Taaca and M. Vasquez Jr. Micropor. Mesopor. Mat. 2017, 241, 383-391.", class: "form-control" %>
        </div>

        <div class="actions d-flex justify-content-center pt-1">
          <%= f.submit "Submit", class: "btn btn-gray btn-margin btn-wide" %>
        </div>
      <% end %>
    </div>
  </div>
</div>


app/views/abstracts/index.html.erb
<div class="table-container p-4 bg-white">
  <h3 class="text-center">All abstracts: <%= @abstracts.count %></h3>
  <p class="text-center">
    <%= link_to 'Download as Excel for Reviewers', abstracts_path(format: :xlsx)%>
  </p>
  <table class="table table-hover table-responsive-md text">
    <thead class="text-gray">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Body Name</th>
    </tr>
    </thead>
    <tbody class="text-gray">
      <% @abstracts.each do |abstract| %>
        <tr>
          <td class="text"><%= abstract.title %></td>
          <td class="text"><%= abstract.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/abstracts/new.html.erb
<div class="d-flex justify-content-center">
  <div class="card flex-column shadow p-3 mb-5 bg-body rounded" style="width: 40rem;">
    <h2 class="text-center">Abstract Submission</h2>
    <p class="text-center italic"> Fill in all details unless tagged as optional and follow instructions to ensure correct format to be printed in Book of Abstracts.</p>
    <div class="form-container">
      <%= form_with model: [ @user, @abstract ], local: true do |f| %>
        <% if @abstract.errors.any? %>
          <div id="error_explanation">
            <h5>The form contains <%= pluralize(@abstract.errors.count, "error") %></h5>
            <ul>
              <% @abstract.errors.full_messages.each do |m| %>
                <li><%= m %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-group mb-6">
          <%= f.label :title, class:"bold" %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "title",
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :main_author, class:"bold" %><br />
          <%= f.select( :main_author,  options_for_select(User.all.collect {|user| [user.get_fullname, user.id ]}, :selected =>params[:user_id]), {},
            { class: "form-select form-select-md mb-6" } ) %>
        </div>

        <div class="field form-group mb-6">

          <%= f.label :co_authors, class:"bold"  %><br />
            <span class="italic small">
              Ensure that all your co-authors are signed up to this web page, otherwise their names will not be among the options below.
              <ul>
                <li class="italic">For one co-author: Single left click one name from options.</li>
                <li class="italic">For multiple co-authors:<br />
                  1. Single left click one name from options. <br />
                  2. Press CTRL , scroll to look for next name and left click when found. <br />
                  3. Repeat step 2 for all co-authors. Chosen names should be blue-colored. </li>
              </ul>
            </span>
          <%= f.select( :co_authors, User.all.collect {|user| [user.get_fullname, user.id ]}, {}, { :multiple=> true, class: "form-select form-select-md mb-6" } ) %>
        </div>

        <div class="field form-group mb-6">
          <span class="bold">Email:</span>
          <%= f.email_field :corresponding_author_email, autofocus: true,
              autocomplete: "email", placeholder: "example@example.com",
              class: "form-control"  %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :keywords, class:"bold" %><br />
            <span class="italic small">
              Must have maximum of five and separated by comma.
            </span>
          <%= f.text_field :keywords, autofocus: true, autocomplete: "keywords",
              placeholder: "vacuum, plasma, nanomaterial",
              class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :body, class:"bold" %><br />
          <%= f.text_area :body, size: "25x10", class: "form-control" %>
        </div>

        <div class="field form-group mb-6">
          <%= f.label :references, class:"bold" %><br />
          <span class="italic small">
            Please follow specific format:
            <ul>
              <li class="italic ">For one reference type: <br />
                [1] S. Trolier-McKinstry, Springer, 2008, 39-56.</li>
              <li class="italic ">For multiple references: <br />
                [1] S. Trolier-McKinstry, Springer, 2008, 39-56.<br />
                [2] K. Taaca and M. Vasquez Jr. Micropor. Mesopor. Mat. 2017, 241, 383-391.<br />
                1. Type the first reference. <br />
                2. Press ENTER and type the next reference. <br />
                3. Repeat step 2 for all references. <br /></li>
            </ul>
          </span>
          <%= f.text_area :references, size: "25x3", placeholder: "[1] K. Taaca and M. Vasquez Jr. Micropor. Mesopor. Mat. 2017, 241, 383-391.", class: "form-control" %>
        </div>

        <div class="actions d-flex justify-content-center pt-1">
          <%= f.submit "Submit", class: "btn btn-gray btn-margin btn-wide" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/abstracts/show.html.erb
<div class="home-container p-4 bg-white">
  <div class="table-container p-4 bg-white">
    <% if user_signed_in? %>
      <h3 class="text-center"><%= @abstract.title.upcase %></h3>
      <p class="text-center"><span class="underline"><%= @user.first_name %> <%= @user.last_name.upcase %></span>,
        <% if @co_authors_fullname.length >= 2 %>
          <%  last = @co_authors_fullname[-1]%>
          <%  list = @co_authors_fullname[0..-2].join(", ")+ "," + " " + last%>
        <%  elsif @co_authors_fullname.length == 1 %>
          <% list = @co_authors_fullname.join() %>
        <% end %>
        <%= list %>
      </p>

      <div class="text-center italic small-text">
        <%= @user.department %>, <%= @user.university_institute_company %>,
          <%= @user.city %>, <%= @user.country %>; <br>
        <span>
            <% if @co_authors_affiliation.length >= 2 %>
              <%  last = @co_authors_affiliation[-1]%>
              <%  list = @co_authors_affiliation[0..-2].join("; \r\n")+ "; \r\n" + " " + last%>
            <%  elsif @co_authors_affiliation.length == 1 %>
              <% list = @co_authors_affiliation.join("; \r\n") %>
            <% end %>
            <%= sanitize(list).gsub(/(\r)?\n/, "<br/>").html_safe %>
       </span>
       <br>
       Email: <%= @abstract.corresponding_author_email %>
     </div>
     <br>
      <p class="justify"> <%= @abstract.body %> <br></p>
      <p class="text-center"> <strong>Keywords:</strong>
        <%if @abstract.keywords.is_a? Array  %>
          <%= @abstract.keywords.join(", ") %>
        <% elsif @abstract.keywords.is_a? String %>
          <%= @abstract.keywords %>
        <% end %>
      </p>
      <p class="text-center"> <strong>References:</strong><br>
        <% if @abstract.references.is_a? Array  %>
          <%= sanitize(@abstract.references.join(",\r\n")).gsub(/(\r)?\n/, "<br/>").html_safe %>
        <% elsif @abstract.references.is_a? String %>
          <%= sanitize(@abstract.references.split(",\r\n").join(",\r\n")).gsub(/(\r)?\n/, "<br/>").html_safe %>
        <% end %>
      </p>

      <p class="text-center"><%= link_to 'Edit This Abstract', edit_user_abstract_path(@user, @abstract), class: "btn btn-gray" %>
      </p>
      <p class="text-center"><%= link_to 'My Conference Details', user_participation_profile_path(@user, @participation), class: "btn btn-gray" %>
      </p>
    <% end %>
  </div>
</div>